### ISSUE TITLE
Missing smoothing on toolpath results ?

### ISSUE THREAD

**Issue by yvanblanchard** [GuoxinFang/MultiAxis3DPrinting_ToolpathGenerator#1]
Hello Guoxin,

I think there is a missing Smoothing step on path results (here, image based on the sample mesh file): 
![image](https://user-images.githubusercontent.com/63931618/157475328-21019640-69fa-47ec-ab87-3e5fd6b017bd.png)

Coudl you please confirm ? 
Thank you.

**Comment by GuoxinFang** [comment]
Hi Yvan,

The issue is solved by adding the refinement function before computing the boundary-distance field.

Guoxin
